---
port: 7890
socks-port: 7891
redir-port: 7892
tproxy-port: 7893
# 混合端口 HTTP和SOCKS5用一个端口
mixed-port: 7893 
#允许局域网的连接（可用来共享代理）
allow-lan: true
# 设置日志输出级别 (5 个级别：silent / error / warning / info / debug）
log-level: info
# 仅在将allow-lan设置为true时适用
#"*": 绑定所有IP地址
bind-address: "*"
# 规则模式：rule（规则） / global（全局代理）/ direct（全局直连）/ script (脚本)
mode: rule
# 开启 IPv6 总开关，关闭阻断所有 IPv6 链接和屏蔽 DNS 请求 AAAA 记录
ipv6: false
interface-name: pppoe-wan
#启用data数据库#【Meta专属】使用geoip.dat数据库(默认：false使用mmdb数据库)
geodata-mode: true
##【Meta专属】*TCP  并发请求所有 IP 地址，然后选择延迟最低的一个进行连接
tcp-concurrent: false
#Geodata 数据加载方式 标准模式
geodata-loader: standard
#启用统一延迟更换延迟计算方式，通过去除握手等额外开销来降低延迟数值
unified-delay: true
#外部控制器,可以使用 RESTful API 来控制你的 clash 内核
external-controller: 127.0.0.1:9090
geox-url:             #自定义 geodata url
  mmdb: "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/country-lite.mmdb"
  geoip: "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.dat"
  geosite: "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat"
hosts:
profile:
    store-selected: true      # 存储 select 选择记录
    store-fake-ip: false        # 持久化 fake-ip
dns:
  enable: true
  listen: '127.0.0.1:53'
  ipv6: false
  use-hosts: true
  prefer-h3: true # 开启 DoH 支持 HTTP/3，将并发尝试
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16 
  default-nameserver: #解析非IP的dns用的dns服务器,只支持纯IP
   - 114.114.114.114 # default value
   - 223.5.5.5
   - 8.8.8.8
  nameserver-policy:  #按指定策略分流 DNS ，可以使用 geosite 分流 DNS 解析。如果是国内就用运营商dns，其他返给默认DNS服务器解析
   geosite:cn,private,apple:
   - 202.102.152.3
   - 202.102.154.3
  fake-ip-filter:   #这里可以填写不使用fakeip的域名
        - '*.lan'
        - '*.battlenet.com.cn'
        - '*.battlenet.com'
        - '*.blzstatic.cn'
        - '*.battle.net'
        # === Linksys Wireless Router ===
        - '*.linksys.com'
        - '*.linksyssmartwifi.com'
        # === Apple Software Update Service ===
        - 'swscan.apple.com'
        - 'mesu.apple.com'
        # === Windows 10 Connnect Detection ===
        - '*.msftconnecttest.com'
        - '*.msftncsi.com'
        # === NTP Service ===
        - 'time.*.com'
        - 'time.*.gov'
        - 'time.*.edu.cn'
        - 'time.*.apple.com'
        - 'time1.*.com'
        - 'time2.*.com'
        - 'time3.*.com'
        - 'time4.*.com'
        - 'time5.*.com'
        - 'time6.*.com'
        - 'time7.*.com'
        - 'ntp.*.com'
        - 'ntp.*.com'
        - 'ntp1.*.com'
        - 'ntp2.*.com'
        - 'ntp3.*.com'
        - 'ntp4.*.com'
        - 'ntp5.*.com'
        - 'ntp6.*.com'
        - 'ntp7.*.com'
        - '*.time.edu.cn'
        - '*.ntp.org.cn'
        - '+.pool.ntp.org'
        - 'time1.cloud.tencent.com'
        # === Music Service ===
        ## NetEase
        - '+.music.163.com'
        - '*.126.net'
        ## Baidu
        - 'musicapi.taihe.com'
        - 'music.taihe.com'
        ## Kugou
        - 'songsearch.kugou.com'
        - 'trackercdn.kugou.com'
        ## Kuwo
        - '*.kuwo.cn'
        ## JOOX
        - 'api-jooxtt.sanook.com'
        - 'api.joox.com'
        - 'joox.com'
        ## QQ
        - '*.qq.com'
        - 'report.url.cn'
        ## Xiami
        - '*.xiami.com'
        ## Migu
        - '+.music.migu.cn'
        # === Game Service ===
        ## Nintendo Switch
        - '+.srv.nintendo.net'
        ## Sony PlayStation
        - '+.playstation.net'
        - '+.playstation.com'
        - '+.stun.playstation.net'
        ## Microsoft Xbox
        - 'xbox.*.microsoft.com'
        - '+.xboxlive.com'
        # === Other ===
        ## QQ Quick Login
        - 'localhost.ptlogin2.qq.com'
        ## Golang
        - 'proxy.golang.org'
        ## STUN Server
        - 'stun.*.*'
        - 'stun.*.*.*'
        ## Bilibili CDN
        - '*.mcdn.bilivideo.cn'
        # === Other ===
        - '*.bilibili.com'
        - '*.1huizhan.com'
        - '*.3.cn'
        - '*.300hu.com'
        - '*.360buy.cn'
        - '*.360buy.com'
        - '*.360buy.com.cn'
        - '*.360buyimg.com'
        - '*.360buyinternational.com'
        - '*.360top.com'
        - '*.jd.com'
  nameserver: #默认DNS服务器，支持udp/tcp/dot/doh/doq
   - tls://8.8.4.4#DNS
   - tls://208.67.222.222#DNS
   - https://dns.alidns.com/dns-query#h3=true # 强制 HTTP/3，与 perfer-h3 无关，强制开启 DoH 的 HTTP/3 支持，若不支持将无法使用
   - https://doh.apad.pro/dns-query 
sniffer:
  #启用嗅探
  enable: true
  #强制探测（嗅探）所有纯 IP 的连接
  parse-pure-ip: false
  force-domain: #列表中的域名将会强制进行探测（嗅探）
  - "+.netflix.com"
  - "+.nflxvideo.net"
  - "+.amazonaws.com"
  - "+.media.dssott.com"
  skip-domain: #列表中的域名（sni）不会进行探测（嗅探）
  - "+.apple.com"
  - Mijia Cloud
  - dlg.io.mi.com
  sniff: #仅探测（嗅探）列表中指定的协议端口
    TLS:               # TLS 默认嗅探 443
      ports: [443, 8443]
    HTTP:
      ports: [80, 8080-8880]
      # 是否使用嗅探结果作为实际访问，默认 true
      override-destination: true
    QUIC:
      ports: [443, 8443]
proxy-providers:
  123:
    type: http
    path: "./proxy_provider/123.yaml"
    url: #填写自己的订阅地址
    interval: 86400
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 36000
tunnels:
proxy-groups:
- name: 全球连接
  type: select
  disable-udp: false
  proxies:
  - 直接连接
  - REJECT
  use:
  - NFCLOUD
- name: Telegram
  type: select
  disable-udp: false
  proxies:
  - 全球连接
  - 直接连接
  use:
  - NFCLOUD
- name: YouTube
  type: select
  disable-udp: false
  proxies:
  - 全球连接
  - 直接连接
  use:
  - NFCLOUD
- name: Netflix
  type: select
  disable-udp: false
  proxies:
  - 全球连接
  - 新加坡
  - 香港
  - 日本
  - 美国
  - 台湾
  use:
  - NFCLOUD
- name: Spotify
  type: select
  disable-udp: false
  proxies:
  - 全球连接
  - 直接连接
  - REJECT
  use:
  - NFCLOUD
- name: Speedtest
  type: select
  disable-udp: false
  proxies:
  - 直接连接
  use:
  - NFCLOUD
- name: 苹果服务
  type: select
  disable-udp: false
  proxies:
  - 全球连接
  - 直接连接
  use:
  - NFCLOUD
- name: OpenAI
  type: select
  disable-udp: false
  proxies:
  - 全球连接
  - 直接连接
  - 新加坡
  - 香港
  - 日本
  - 美国
  - 台湾
  use:
  - NFCLOUD
- name: Copilot
  type: select
  disable-udp: false
  proxies:
  - 全球连接
  - 直接连接
  - 新加坡
  - 香港
  - 日本
  - 美国
  - 台湾
  use:
  - NFCLOUD
- name: TikTok
  type: select
  disable-udp: false
  proxies:
  - 直接连接
  - 新加坡
  - 台湾
  - 日本
  - 美国
  use:
  - NFCLOUD
- name: 新加坡
  type: url-test
  disable-udp: false
  use:
  - NFCLOUD
  url: http://www.gstatic.com/generate_204
  interval: 21600
  tolerance: 50
  filter: "新加坡|坡|狮城|\U0001F1F8\U0001F1EC|SG|(?i)Singapore"
- name: 香港
  type: url-test
  disable-udp: false
  use:
  - NFCLOUD
  url: http://www.gstatic.com/generate_204
  interval: 21600
  tolerance: 50
  filter: "澳门|\U0001F1F2\U0001F1F4|港|\U0001F1ED\U0001F1F0|HK|(?i)Hong"
- name: 台湾
  type: url-test
  disable-udp: false
  use:
  - NFCLOUD
  url: http://www.gstatic.com/generate_204
  interval: 21600
  tolerance: 50
  filter: "台|\U0001F1F9\U0001F1FC|湾|TW|(?i)Taiwan"
- name: 日本
  type: url-test
  disable-udp: false
  use:
  - NFCLOUD
  url: http://www.gstatic.com/generate_204
  interval: 21600
  tolerance: 50
  filter: "日|\U0001F1EF\U0001F1F5|东京|JP|(?i)Japan"
- name: 美国
  type: url-test
  disable-udp: false
  use:
  - NFCLOUD
  url: http://www.gstatic.com/generate_204
  interval: 21600
  tolerance: 50
  filter: "美|\U0001F1FA\U0001F1F2|US|(?i)States|America"
- name: 漏网之鱼
  type: select
  disable-udp: false
  proxies:
  - 直接连接
  - 全球连接
- name: 屏蔽苹果系统更新
  type: select
  disable-udp: true
  proxies:
  - 直接连接
  - REJECT
  filter: "DIRECT|REJECT|直接连接"
- name: 直接连接
  type: select
  disable-udp: false
  proxies:
  - DIRECT
  filter: "DIRECT"
script:
  shortcuts:
    quic: network == 'udp' and dst_port == 443
rule-providers:
  国内直连:
    type: http
    behavior: classical
    path: "/etc/openclash/rule_provider/China.yaml"
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/China.yaml
    interval: 86400
  国内IP:
    type: http
    behavior: ipcidr
    path: "/etc/openclash/rule_provider/ChinaIP.yaml"
    url: https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/cncidr.txt
    interval: 86400   
  Global:
    type: http
    behavior: classical
    path: "/etc/openclash/rule_provider/Global.yaml"
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Global.yaml
    interval: 86400
  WeChat:
    type: http
    behavior: classical
    path: "/etc/openclash/rule_provider/WeChat.yaml"
    url:  https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/WeChat/WeChat.yaml
    interval: 86400
    
  局域网络:
    type: http
    behavior: classical
    path: "/etc/openclash/rule_provider/Lan.yaml"
    url: https://raw.githubusercontent.com/65222/Configuration/main/Clash/Rule/Lan.txt
    interval: 86400
    
  Telegram:
    type: http
    behavior: classical
    path: "/etc/openclash/rule_provider/Telegram.yaml"
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Extra/Telegram/Telegram.yaml
    interval: 86400
  抖音:
    type: http
    behavior: classical
    path: "/etc/openclash/rule_provider/DouYin.yaml"
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/DouYin/DouYin.yaml
    interval: 86400
  GitHub:
    type: http
    behavior: classical
    path: "/etc/openclash/rule_provider/GitHub.yaml"
    url: https://raw.githubusercontent.com/LM-Firefly/Rules/master/Clash-RuleSet-Classical/PROXY/Github.yaml
    interval: 86400
  Google:
    type: http
    behavior: classical
    path: "/etc/openclash/rule_provider/Google.yaml"
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Google/Google.yaml
    interval: 86400
  Instagram:
    type: http
    behavior: classical
    path: "/etc/openclash/rule_provider/Instagram.yaml"
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Instagram/Instagram.yaml
    interval: 86400
  Netflix:
    type: http
    behavior: classical
    path: "/etc/openclash/rule_provider/Netflix.yaml"
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/StreamingMedia/Video/Netflix.yaml
    interval: 86400
  Spotify:
    type: http
    behavior: classical
    path: "/etc/openclash/rule_provider/Spotify.yaml"
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/StreamingMedia/Music/Spotify.yaml
    interval: 86400
  Twitter:
    type: http
    behavior: classical
    path: "/etc/openclash/rule_provider/Twitter.yaml"
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Twitter/Twitter.yaml
    interval: 86400
  YouTube:
    type: http
    behavior: classical
    path: "/etc/openclash/rule_provider/YouTube.yaml"
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/StreamingMedia/Video/YouTube.yaml
    interval: 86400
  OpenAI:
    type: http
    behavior: classical
    path: "/etc/openclash/rule_provider/OpenAI.yaml"
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OpenAI/OpenAI.yaml
    interval: 86400
  Speedtest:
    type: http
    behavior: classical
    path: "/etc/openclash/rule_provider/Speedtest.yaml"
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Speedtest/Speedtest.yaml
    interval: 86400 
  屏蔽苹果系统更新:
    type: http
    behavior: classical
    path: "/etc/openclash/rule_provider/SoftwareUpdate.yaml"
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Extra/Apple/SoftwareUpdate.yaml
    interval: 86400
  Copilot:
    type: http
    behavior: classical
    format: text
    path: "/etc/openclash/rule_provider/Copilot.yaml"
    url: https://raw.githubusercontent.com/Repcz/Tool/X/Clash/Rules/Copilot.list
    interval: 86400
  TikTok:
    type: http
    behavior: classical
    path: "/etc/openclash/rule_provider/TikTok.yaml"
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/StreamingMedia/Video/TikTok.yaml
    interval: 86400
  Apple:
    type: http
    behavior: domain
    path: "/etc/openclash/rule_provider/Apple.yaml"    
    url: https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/apple.txt
    interval: 86400
  applications:
    type: http
    behavior: domain
    path: "/etc/openclash/rule_provider/applications.yaml"    
    url: https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/applications.txt
    interval: 86400
  private:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/private.txt
    path: "/etc/openclash/rule_provider/private.yaml" 
    interval: 86400   
  icloud:
    type: http
    behavior: domain
    path: "/etc/openclash/rule_provider/applications.yaml"    
    url: https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/icloud.txt
    interval: 86400    
rules:
- SRC-IP-CIDR,192.168.20.16/32,DIRECT,no-resolve
- RULE-SET,局域网络,直接连接
- DOMAIN,sub-store.vercel.app,全球连接
- DOMAIN,loon-plugin.vercel.app,全球连接
- DOMAIN-KEYWORD,missav,全球连接
- DOMAIN-KEYWORD,pixabay,全球连接
- RULE-SET,Copilot,Copilot
- RULE-SET,applications,DIRECT
- RULE-SET,private,DIRECT
- RULE-SET,WeChat,直接连接
- RULE-SET,Speedtest,直接连接
- GEOSITE,steam@cn,DIRECT
- GEOSITE,category-games@cn,DIRECT
- GEOSITE,apple@cn,DIRECT
- GEOSITE,apple-cn,DIRECT
- GEOSITE,wikimedia,全球连接
- GEOSITE,facebook,全球连接
- RULE-SET,TikTok,TikTok
- RULE-SET,YouTube,YouTube
- RULE-SET,Google,全球连接
- RULE-SET,GitHub,全球连接
- RULE-SET,Instagram,全球连接
- RULE-SET,Twitter,全球连接
- RULE-SET,Netflix,Netflix
- RULE-SET,Telegram,Telegram
- RULE-SET,Spotify,Spotify
- RULE-SET,OpenAI,OpenAI
- RULE-SET,屏蔽苹果系统更新,屏蔽苹果系统更新
- RULE-SET,icloud,苹果服务
- RULE-SET,Apple,苹果服务
- RULE-SET,抖音,直接连接
- RULE-SET,国内直连,直接连接
- SRC-PORT,7777,DIRECT
- SRC-IP-CIDR,192.168.1.201/32,DIRECT
- IP-CIDR,127.0.0.0/8,DIRECT
- GEOIP,google,全球连接,no-resolve
- GEOIP,telegram,Telegram,no-resolve
- GEOIP,netflix,Netflix,no-resolve
- GEOIP,twitter,全球连接,no-resolve
- GEOIP,private,DIRECT,no-resolve
- GEOIP,LAN,DIRECT
- GEOIP,CN,DIRECT
#- DST-PORT,80,漏网之鱼
- MATCH,漏网之鱼    
